name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-focal
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Z3
        uses: pavpanchekha/setup-z3@1.2.2
        with:
          version: 4.8.9
      - name: Install GTest
        uses: MarkusJx/googletest-installer@v1.1
      - name: Install ROS
        uses: ros-tooling/setup-ros@0.1.4
        with:
          required-ros-distributions: noetic
      - name: Install other dependencies
        run: sudo apt-get install -yq libeigen3-dev libgoogle-glog-dev
      - name: Build
        run: make
      - name: Run unit tests
        run: ./bin/unit-tests
